/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proizvod;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Timer;

/**
 *
 * @author Freeware Sys
 */
public class AzuriranjeProizvoda extends javax.swing.JFrame {
SQLProizvod sqlProizvod = new SQLProizvod();
    /**
     * Creates new form AzuriranjeProizvoda
     */
    public AzuriranjeProizvoda() {
        initComponents();
        popuniProizvod();
        zamjeni();
        /*Timer timer = new Timer(10, new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                AzuriranjeProizvoda.this.repaint();
            }

        });
        timer.start();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSifraProizvoda = new javax.swing.JTextField();
        txtNazivProizvoda = new javax.swing.JTextField();
        txtCijenaProizvoda = new javax.swing.JTextField();
        txtKolicinaProizvoda = new javax.swing.JTextField();
        btnKreiraj = new javax.swing.JButton();
        btnIzmjeni = new javax.swing.JButton();
        btnBrisanje = new javax.swing.JButton();
        cmbProizvod = new javax.swing.JComboBox<>();
        btnIzbornikProizvoda = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnOcisti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sifra proizvoda:");

        jLabel2.setText("Naziv proizvoda:");

        jLabel3.setText("Cijena proizvoda:");

        jLabel4.setText("Količina proizvoda:");

        txtSifraProizvoda.setEditable(false);
        txtSifraProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifraProizvodaActionPerformed(evt);
            }
        });

        btnKreiraj.setText("Kreiraj");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        btnIzmjeni.setText("Izmjeni");
        btnIzmjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjeniActionPerformed(evt);
            }
        });

        btnBrisanje.setText("Obriši");
        btnBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeActionPerformed(evt);
            }
        });

        cmbProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProizvodActionPerformed(evt);
            }
        });

        btnIzbornikProizvoda.setText("Izbornik proizvoda");
        btnIzbornikProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbornikProizvodaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Ažuriranje proizvoda");

        btnOcisti.setText("Očisti");
        btnOcisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnIzbornikProizvoda)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSifraProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCijenaProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtKolicinaProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnKreiraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIzmjeni)
                                .addGap(193, 193, 193)
                                .addComponent(btnBrisanje))
                            .addComponent(btnOcisti, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addComponent(cmbProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifraProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCijenaProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKolicinaProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrisanje)
                    .addComponent(btnIzmjeni)
                    .addComponent(btnKreiraj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzbornikProizvoda)
                    .addComponent(btnOcisti))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        // TODO add your handling code here:
        int sifraProizvoda = Integer.parseInt(txtSifraProizvoda.getText());
        String nazivProizvoda = txtNazivProizvoda.getText();
        float cijenaProizvoda = Float.parseFloat(txtCijenaProizvoda.getText());
        int kolicinaProizvoda = Integer.parseInt(txtKolicinaProizvoda.getText());
        
        Proizvod proizvod = new Proizvod();
        proizvod.setSifraProizvoda(sifraProizvoda);
        proizvod.setNazivProizvoda(nazivProizvoda);
        proizvod.setCijenaProizvoda(cijenaProizvoda);
        proizvod.setKolicinaProizvoda(kolicinaProizvoda);
        
        sqlProizvod.spremi(proizvod);
        
        
        obrisiProizvod();
        popuniProizvod();
        
        txtSifraProizvoda.setText("");
        txtNazivProizvoda.setText("");
        txtCijenaProizvoda.setText("");
        txtKolicinaProizvoda.setText("");
        
        
    }//GEN-LAST:event_btnKreirajActionPerformed

    private void btnIzmjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjeniActionPerformed
        // TODO add your handling code here:
        int sifraProizvoda = Integer.parseInt(txtSifraProizvoda.getText());
        String nazivProizvoda = txtNazivProizvoda.getText();
        float cijenaProizvoda = Float.parseFloat(txtCijenaProizvoda.getText());
        int kolicinaProizvoda = Integer.parseInt(txtKolicinaProizvoda.getText());
        
        
        
        Proizvod proizvod = new Proizvod();
        proizvod.setSifraProizvoda(sifraProizvoda);
        proizvod.setCijenaProizvoda(cijenaProizvoda);
        proizvod.setNazivProizvoda(nazivProizvoda);
        proizvod.setKolicinaProizvoda(kolicinaProizvoda );
        
        sqlProizvod.IzmjenaSVE(proizvod);
        
        obrisiProizvod();
        popuniProizvod();
        
    }//GEN-LAST:event_btnIzmjeniActionPerformed

    private void btnBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeActionPerformed
        // TODO add your handling code here:
        Proizvod proizvod = new Proizvod();
        int sifraProizvoda = Integer.parseInt(txtSifraProizvoda.getText());
        proizvod.setSifraProizvoda(sifraProizvoda);
        sqlProizvod.Brisanje(proizvod);
        
        obrisiProizvod();
        popuniProizvod();
        
    }//GEN-LAST:event_btnBrisanjeActionPerformed

    private void cmbProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProizvodActionPerformed
        txtNazivProizvoda.setText(cmbProizvod.getSelectedItem().toString());
        Proizvod selProizvod = (Proizvod)cmbProizvod.getSelectedItem();
        txtSifraProizvoda.setText(Integer.toString(selProizvod.getSifraProizvoda()));
        txtCijenaProizvoda.setText(Float.toString(selProizvod.getCijenaProizvoda()));
        txtKolicinaProizvoda.setText(Integer.toString(selProizvod.getKolicinaProizvoda()));
        txtCijenaProizvoda.setEditable(true);
    }//GEN-LAST:event_cmbProizvodActionPerformed

    private void btnIzbornikProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbornikProizvodaActionPerformed
        IzbornikProizvoda izbornikProizvoda = new IzbornikProizvoda();
        izbornikProizvoda.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIzbornikProizvodaActionPerformed

    private void txtSifraProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifraProizvodaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifraProizvodaActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed
        // TODO add your handling code here:
        txtSifraProizvoda.setText("");
        txtNazivProizvoda.setText("");
        txtCijenaProizvoda.setEditable(true);
        txtCijenaProizvoda.setText("");
        txtKolicinaProizvoda.setText("");
        autoinkrementacijaProizvoda();
    }//GEN-LAST:event_btnOcistiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AzuriranjeProizvoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AzuriranjeProizvoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AzuriranjeProizvoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AzuriranjeProizvoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AzuriranjeProizvoda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanje;
    private javax.swing.JButton btnIzbornikProizvoda;
    private javax.swing.JButton btnIzmjeni;
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JComboBox<Proizvod> cmbProizvod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCijenaProizvoda;
    private javax.swing.JTextField txtKolicinaProizvoda;
    private javax.swing.JTextField txtNazivProizvoda;
    private javax.swing.JTextField txtSifraProizvoda;
    // End of variables declaration//GEN-END:variables
private void popuniProizvod(){
    ArrayList<Proizvod>listaProizvoda = sqlProizvod.listaProizvoda();
    for(Proizvod proizvod: listaProizvoda){
       cmbProizvod.addItem(proizvod);
    }
}

private void obrisiProizvod(){
    
      cmbProizvod.setModel(new DefaultComboBoxModel());
    
}
private void zamjeni(){
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
 private void autoinkrementacijaProizvoda(){
        int sifra = 0;
        ArrayList<Proizvod>listaProizvoda = sqlProizvod.listaProizvoda();
        for(Proizvod proizvod: listaProizvoda){
            
            sifra = proizvod.getSifraProizvoda();
        }
        if(sifra == 0){
        sifra = 1;
        txtSifraProizvoda.setText(Integer.toString(sifra));
        }
        else{
            txtSifraProizvoda.setText(Integer.toString(sifra+1));
        }
    }
}
