/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proizvod;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Freeware Sys
 */
public class IzvjestajProizvodi extends javax.swing.JFrame {
    
    
    SQLProizvod sqlProizvod = new SQLProizvod();

    /**
     * Creates new form IzvjestajProizvodi
     */
    public IzvjestajProizvodi() {
        initComponents();
        popuniProizvod();
        zamjeni();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProizvod = new javax.swing.JTable();
        txtSifraP = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        btnOsvjezi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIzbornikProizvoda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableProizvod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Šifra proizvoda", "Naziv proizvoda", "Cijena proizvoda", "Količina proizvoda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableProizvod);
        if (TableProizvod.getColumnModel().getColumnCount() > 0) {
            TableProizvod.getColumnModel().getColumn(0).setResizable(false);
            TableProizvod.getColumnModel().getColumn(1).setResizable(false);
            TableProizvod.getColumnModel().getColumn(2).setResizable(false);
            TableProizvod.getColumnModel().getColumn(3).setResizable(false);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnOsvjezi.setText("Osvježi");
        btnOsvjezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsvjeziActionPerformed(evt);
            }
        });

        jLabel1.setText("Šifra proizvoda:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Pregled proizvoda");

        btnIzbornikProizvoda.setText("Izbornik proizvoda");
        btnIzbornikProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbornikProizvodaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSifraP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOsvjezi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzbornikProizvoda)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOsvjezi)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretrazi)
                    .addComponent(txtSifraP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnIzbornikProizvoda)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        int sifra=0;
        String naziv="";    
        Proizvod proizvod = new Proizvod();
        sifra = Integer.parseInt(txtSifraP.getText().trim());
        sqlProizvod.setSifraA(sifra);
        ponovanIspis();
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnOsvjeziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsvjeziActionPerformed
        txtSifraP.setText("");
        ArrayList<Proizvod>listaProizvoda = sqlProizvod.listaProizvoda();
    DefaultTableModel model = (DefaultTableModel) TableProizvod.getModel();
    while(model.getRowCount()>0){
            for (int i = 0; i < TableProizvod.getRowCount(); i++) {
          model.removeRow(i);
      }}
    for(Proizvod proizvod: listaProizvoda){
       model.addRow(new Object[]{proizvod.getSifraProizvoda(),proizvod.getNazivProizvoda(),proizvod.getCijenaProizvoda(),proizvod.getKolicinaProizvoda()});       
    }
    }//GEN-LAST:event_btnOsvjeziActionPerformed

    private void btnIzbornikProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbornikProizvodaActionPerformed
        // TODO add your handling code here:
        IzbornikProizvoda izbornik = new IzbornikProizvoda();
        izbornik.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIzbornikProizvodaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzvjestajProizvodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzvjestajProizvodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzvjestajProizvodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzvjestajProizvodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IzvjestajProizvodi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableProizvod;
    private javax.swing.JButton btnIzbornikProizvoda;
    private javax.swing.JButton btnOsvjezi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtSifraP;
    // End of variables declaration//GEN-END:variables

private void popuniProizvod(){
    ArrayList<Proizvod>listaProizvoda = sqlProizvod.listaProizvoda();
    
    DefaultTableModel model = (DefaultTableModel) TableProizvod.getModel();
    
    for(Proizvod proizvod: listaProizvoda){
       
       model.addRow(new Object[]{proizvod.getSifraProizvoda(),proizvod.getNazivProizvoda(),proizvod.getCijenaProizvoda(),proizvod.getKolicinaProizvoda()});

       
    }
}

private void ponovanIspis() {
    
            DefaultTableModel model = (DefaultTableModel) TableProizvod.getModel();
         
         while(model.getRowCount()>0){
            for (int i = 0; i < TableProizvod.getRowCount(); i++) {
          model.removeRow(i);
      }
         }
       ArrayList<Proizvod>listaProizvoda = sqlProizvod.listaProizvodaS();
       
       for(Proizvod proizvod: listaProizvoda){
       
           model.addRow(new Object[]{proizvod.getSifraProizvoda(),proizvod.getNazivProizvoda(),proizvod.getCijenaProizvoda(),proizvod.getKolicinaProizvoda()});
       }
    }
private void zamjeni(){
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
}

