/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Racuni;

import Kupac.Kupac;
import Kupac.SQLKupac;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shpekula
 */
public class PregledRacunaPoGod extends javax.swing.JFrame {
SQLRacun sqlRacun = new SQLRacun();
SQLKupac sqlKupac = new SQLKupac();
    /**
     * Creates new form PregledPDVPoGod
     */
    public PregledRacunaPoGod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablica = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtGodina = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOsnovica = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPDV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUkupno = new javax.swing.JTextField();
        btnPovratak = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnOsvjezi = new javax.swing.JButton();
        btnPretraziPoGod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Šifra računa", "Datum", "Naziv kupca", "Iznos računa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablica);

        jLabel1.setText("Unesite godinu:");

        jLabel2.setText("Osnovica:");

        txtOsnovica.setEditable(false);

        jLabel3.setText("PDV:");

        txtPDV.setEditable(false);

        jLabel4.setText("Ukupno:");

        txtUkupno.setEditable(false);

        btnPovratak.setText("Povratak");
        btnPovratak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPovratakActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 36)); // NOI18N
        jLabel5.setText("Računi po godini");

        btnOsvjezi.setText("Osvježi");
        btnOsvjezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsvjeziActionPerformed(evt);
            }
        });

        btnPretraziPoGod.setText("Pretraži po godini");
        btnPretraziPoGod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziPoGodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtOsnovica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOsvjezi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPovratak, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPretraziPoGod, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziPoGod))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOsnovica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPovratak)
                    .addComponent(btnOsvjezi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPovratakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPovratakActionPerformed
        dispose();
    }//GEN-LAST:event_btnPovratakActionPerformed

    private void btnOsvjeziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsvjeziActionPerformed
        DefaultTableModel model = (DefaultTableModel)tablica.getModel();
        model.setRowCount(0);
        txtOsnovica.setText("");
        txtPDV.setText("");
        txtUkupno.setText("");
        txtGodina.setText("");
    }//GEN-LAST:event_btnOsvjeziActionPerformed

    private void btnPretraziPoGodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziPoGodActionPerformed
        String god = txtGodina.getText();
        float ukupno = 0;
        float osnovica = 0;
        float PDV = 0;
        int d = 2;
        int sifraKup = 0;
        String nazivKup = null;
        int t = 1;
        int m = 2;
        DefaultTableModel model = (DefaultTableModel)tablica.getModel();
        ArrayList<Kupac>listaKupca = sqlKupac.listaKupaca();
        ArrayList<Racun>listaRacuna = sqlRacun.listaRacuna();
        
        for(Racun racun: listaRacuna){
            int c = 1;
            int sifraRacuna = racun.getSifraRacuna();
            String datum = racun.getDatum();
            int sifraKupca = racun.getSifraKupca();
            float cijenaRacuna = racun.getCijenaRacuna();
            String[] polje = datum.split("-");
            String polje1 = null;
            String polje2 = null;
            String polje3 = null;
            
            polje1 = polje[0];
            polje2 = polje[1];
            polje3 = polje[2];
               for(int n = 0; n < listaRacuna.size();n++){
            
            if(polje3.equals(god)){
                for(Kupac kupac: listaKupca)
            for(int i = 0; i < listaKupca.size();i++){
                sifraKup = kupac.getSifraKupca();
            if(sifraKupca == sifraKup){
                nazivKup = kupac.getNazivKupca();
            if(c<d){ 
            
                model.addRow(new Object[]{sifraRacuna, datum, nazivKup, cijenaRacuna});
            }
            c++;
            }
            }
            }    
               }
        }
        
        if(model.getRowCount()==0){
                    txtGodina.setText("");
                    System.out.print("\nUnesena godina ne postoji!");
                    }
        
        int a = tablica.getRowCount();
        int b = tablica.getColumnCount();
        for(int i = 0; i < a; i++){
            int sifraRacuna = 0;
            String datum = null;
            String nazKup = null;
            float iznosRacuna = 0;
            
            for(int j = 0; j < b; j++){
                sifraRacuna = (int) tablica.getValueAt(i, 0);
                datum = (String) tablica.getValueAt(i, 1);
                nazKup = (String) tablica.getValueAt(i, 2);
                iznosRacuna = (float) tablica.getValueAt(i, 3);
                ukupno += iznosRacuna;
            }
        }
        ukupno=ukupno/4;
        osnovica = (ukupno/125)*100;
        PDV = (ukupno/125)*25;
        
        txtUkupno.setText(Float.toString(ukupno));
        txtOsnovica.setText(Float.toString(osnovica));
        txtPDV.setText(Float.toString(PDV));
    }//GEN-LAST:event_btnPretraziPoGodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PregledRacunaPoGod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PregledRacunaPoGod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PregledRacunaPoGod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PregledRacunaPoGod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PregledRacunaPoGod().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOsvjezi;
    private javax.swing.JButton btnPovratak;
    private javax.swing.JButton btnPretraziPoGod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablica;
    private javax.swing.JTextField txtGodina;
    private javax.swing.JTextField txtOsnovica;
    private javax.swing.JTextField txtPDV;
    private javax.swing.JTextField txtUkupno;
    // End of variables declaration//GEN-END:variables
}
