/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kupac;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import IzgradnjaAplikacijeZaProdajuKorištenjemObjektnogPristupa.Controller;

/**
 *
 * @author Shpekula
 */
public class AzuriranjeKupca extends javax.swing.JFrame {
Controller controll = new Controller();
SQLKupac sqlKupac = new SQLKupac();
    /**
     * Creates new form AzuriranjeKupca
     */
    public AzuriranjeKupca() {
        initComponents();
        popuniKupac();
        zamjeni();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSifraKupca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNazivKupca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAdresaKupca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtOIBKupca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMailKupca = new javax.swing.JTextField();
        txtKontakBrojKupca = new javax.swing.JTextField();
        btnKreirajKupca = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnPovratak = new javax.swing.JButton();
        cmbKupac = new javax.swing.JComboBox<>();
        btnOcisti = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sifra kupca:");

        txtSifraKupca.setEditable(false);

        jLabel2.setText("Naziv kupca:");

        jLabel3.setText("Adresa kupca:");

        jLabel6.setText("OIBKupca:");

        jLabel7.setText("Mail kupca:");

        jLabel8.setText("Kontakt broj kupca:");

        txtKontakBrojKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKontakBrojKupcaActionPerformed(evt);
            }
        });

        btnKreirajKupca.setText("Kreiraj");
        btnKreirajKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajKupcaActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jButton1.setText("Izmjeni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPovratak.setText("Izbornik kupci");
        btnPovratak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPovratakActionPerformed(evt);
            }
        });

        cmbKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKupacActionPerformed(evt);
            }
        });

        btnOcisti.setText("Očisti");
        btnOcisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Ažuriranje kupaca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnOcisti, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPovratak)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbKupac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSifraKupca)
                                    .addComponent(txtNazivKupca)
                                    .addComponent(txtAdresaKupca)
                                    .addComponent(txtOIBKupca)
                                    .addComponent(txtMailKupca)
                                    .addComponent(txtKontakBrojKupca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKreirajKupca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cmbKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifraKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAdresaKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOIBKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMailKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtKontakBrojKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnObrisi)
                    .addComponent(btnKreirajKupca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOcisti)
                    .addComponent(btnPovratak))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajKupcaActionPerformed
        // TODO add your handling code here:
    int sifraKupca = Integer.parseInt(txtSifraKupca.getText());
    String nazivKupca = txtNazivKupca.getText();
    String OIBKupca = txtOIBKupca.getText();
    String AdresaKupca = txtAdresaKupca.getText();
    String mailKupca = txtMailKupca.getText();
    Integer KontaktBrojKupca = Integer.parseInt(txtKontakBrojKupca.getText());
    
    //controll.kreirajKupca(sifraKupca, nazivKupca, OIBKupca, AdresaKupca, mailKupca, KontaktBrojKupca);
    
    Kupac kupac = new Kupac();
    kupac.setSifraKupca(sifraKupca);
    kupac.setNazivKupca(nazivKupca);
    kupac.setOIBKupca(OIBKupca);
    kupac.setAdresaKupca(AdresaKupca);
    kupac.setMailKupca(mailKupca);
    kupac.setKontaktBrojKupca(KontaktBrojKupca);
    
    sqlKupac.spremi(kupac);
    
    obrisiKupac();
    popuniKupac();
    
    txtSifraKupca.setText("");
    txtNazivKupca.setText("");
    txtOIBKupca.setText("");
    txtAdresaKupca.setText("");
    txtMailKupca.setText("");
    txtKontakBrojKupca.setText("");
    
    
    }//GEN-LAST:event_btnKreirajKupcaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int sifraKupca = Integer.parseInt(txtSifraKupca.getText());
        String nazivKupca = txtNazivKupca.getText();
        String AdresaKupca = txtAdresaKupca.getText();
        String OIBKupca = txtOIBKupca.getText();
        String mailKupca = txtMailKupca.getText();
        int KontaktBrojKupca = Integer.parseInt(txtKontakBrojKupca.getText());
        
        Kupac kupac = new Kupac();
        
        kupac.setSifraKupca(sifraKupca);
        kupac.setNazivKupca(nazivKupca);
        kupac.setAdresaKupca(AdresaKupca);
        kupac.setOIBKupca(OIBKupca);
        kupac.setMailKupca(mailKupca);
        kupac.setKontaktBrojKupca(KontaktBrojKupca);
        
        sqlKupac.Izmjena(kupac);
        
        
        obrisiKupac();
        popuniKupac();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        // TODO add your handling code here:
        
        Kupac kupac = new Kupac();
        int sifraKupca = Integer.parseInt(txtSifraKupca.getText());
        kupac.setSifraKupca(sifraKupca);
        sqlKupac.Brisanje(kupac);
        
        obrisiKupac();
        popuniKupac();
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPovratakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPovratakActionPerformed
        // TODO add your handling code here:
        IzbornikKupac izbornik = new IzbornikKupac();
        izbornik.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPovratakActionPerformed

    private void cmbKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKupacActionPerformed
        // TODO add your handling code here:
        
        //txtNazivKupca.setText(cmbKupac.getSelectedItem().toString());
        //txtSifraKupca.setText(cmbKupac.getSelectedItem().toString());
        Kupac selKupac = (Kupac)cmbKupac.getSelectedItem();
        txtSifraKupca.setText(Integer.toString(selKupac.getSifraKupca()));
        txtNazivKupca.setText(selKupac.getNazivKupca());
        txtAdresaKupca.setText(selKupac.getAdresaKupca());
        txtOIBKupca.setText(selKupac.getOIBKupca());
        txtMailKupca.setText(selKupac.getMailKupca());
        txtKontakBrojKupca.setText(Integer.toString(selKupac.getKontaktBrojKupca()));
    }//GEN-LAST:event_cmbKupacActionPerformed

    private void txtKontakBrojKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKontakBrojKupcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKontakBrojKupcaActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed
        // TODO add your handling code here:
        autoinkrementacijaKupca();
        txtNazivKupca.setText("");
        txtAdresaKupca.setText("");
        txtOIBKupca.setText("");
        txtMailKupca.setText("");
        txtKontakBrojKupca.setText("");
    }//GEN-LAST:event_btnOcistiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AzuriranjeKupca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AzuriranjeKupca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AzuriranjeKupca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AzuriranjeKupca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AzuriranjeKupca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajKupca;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnPovratak;
    private javax.swing.JComboBox<Kupac> cmbKupac;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAdresaKupca;
    private javax.swing.JTextField txtKontakBrojKupca;
    private javax.swing.JTextField txtMailKupca;
    private javax.swing.JTextField txtNazivKupca;
    private javax.swing.JTextField txtOIBKupca;
    private javax.swing.JTextField txtSifraKupca;
    // End of variables declaration//GEN-END:variables

    private void popuniKupac(){
    ArrayList<Kupac>listaKupaca = sqlKupac.listaKupaca();
    for(Kupac kupac: listaKupaca){
       cmbKupac.addItem(kupac);
    }
}
    private void obrisiKupac(){
    
      cmbKupac.setModel(new DefaultComboBoxModel());
    
}
    
    private void zamjeni(){
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    private void autoinkrementacijaKupca(){
        int sifra = 0;
        ArrayList<Kupac>listaKupaca = sqlKupac.listaKupaca();
        for(Kupac kupac: listaKupaca){
            
            sifra = kupac.getSifraKupca();
        }
        if(sifra == 0){
        sifra = 1;
        txtSifraKupca.setText(Integer.toString(sifra));
        }
        else{
            txtSifraKupca.setText(Integer.toString(sifra+1));
        }
    }
    
}
