/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kupac;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Freeware Sys
 */
public class IzvjestajKupac extends javax.swing.JFrame {
    SQLKupac sqlKupac = new SQLKupac();

    /**
     * Creates new form IzvjestajKupci
     */
    public IzvjestajKupac() {
        initComponents();
        popuniKupac();
        zamjeni();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablicaKupci = new javax.swing.JTable();
        txtSifraK = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        btnOsvjezi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPovratak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablicaKupci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Šifra kupca", "Naziv kupca", "OIB kupca", "Adresa kupca", "Mail kupca", "Kontakt kupca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablicaKupci);
        if (TablicaKupci.getColumnModel().getColumnCount() > 0) {
            TablicaKupci.getColumnModel().getColumn(0).setResizable(false);
            TablicaKupci.getColumnModel().getColumn(1).setResizable(false);
            TablicaKupci.getColumnModel().getColumn(2).setResizable(false);
            TablicaKupci.getColumnModel().getColumn(3).setResizable(false);
            TablicaKupci.getColumnModel().getColumn(4).setResizable(false);
            TablicaKupci.getColumnModel().getColumn(5).setResizable(false);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        txtSifraK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifraKActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnOsvjezi.setText("Osvježi");
        btnOsvjezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsvjeziActionPerformed(evt);
            }
        });

        jLabel1.setText("Šifra kupca:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("Izvještaj kupci");

        btnPovratak.setText("Izbornik kupci");
        btnPovratak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPovratakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSifraK, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOsvjezi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPovratak)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOsvjezi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSifraK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPovratak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOsvjeziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsvjeziActionPerformed
        txtSifraK.setText("");

        ArrayList<Kupac>listaKupaca = sqlKupac.listaKupaca();
    
    DefaultTableModel model = (DefaultTableModel) TablicaKupci.getModel();
    
    while(model.getRowCount()>0){
            for (int i = 0; i < TablicaKupci.getRowCount(); i++) {
          model.removeRow(i);
      }}
    
    for(Kupac kupac: listaKupaca){
       
       model.addRow(new Object[]{kupac.getSifraKupca(),kupac.getNazivKupca(),kupac.getOIBKupca(),kupac.getAdresaKupca(),kupac.getMailKupca(),kupac.getKontaktBrojKupca()});  
    }
    }//GEN-LAST:event_btnOsvjeziActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed

        int sifra=0;    
        
        Kupac kupac = new Kupac();
        
        sifra = Integer.parseInt(txtSifraK.getText());
        sqlKupac.setSifraA(sifra);
        ponovanIspis();
  

    }//GEN-LAST:event_btnPretraziActionPerformed

    private void txtSifraKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifraKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifraKActionPerformed

    private void btnPovratakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPovratakActionPerformed
        dispose();
    }//GEN-LAST:event_btnPovratakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzvjestajKupac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzvjestajKupac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzvjestajKupac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzvjestajKupac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IzvjestajKupac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablicaKupci;
    private javax.swing.JButton btnOsvjezi;
    private javax.swing.JButton btnPovratak;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtSifraK;
    // End of variables declaration//GEN-END:variables

private void popuniKupac(){
    ArrayList<Kupac>listaKupaca = sqlKupac.listaKupaca();
    
    DefaultTableModel model = (DefaultTableModel) TablicaKupci.getModel();
    
    for(Kupac kupac: listaKupaca){
       
       model.addRow(new Object[]{kupac.getSifraKupca(),kupac.getNazivKupca(),kupac.getOIBKupca(),kupac.getAdresaKupca(),kupac.getMailKupca(),kupac.getKontaktBrojKupca()});

       
    }
}

private void ponovanIspis() {
    
            DefaultTableModel model = (DefaultTableModel) TablicaKupci.getModel();
         
         while(model.getRowCount()>0){
            for (int i = 0; i < TablicaKupci.getRowCount(); i++) {
          model.removeRow(i);
      }
         }
     
       ArrayList<Kupac>listaKupaca = sqlKupac.listaKupacaS();
       
       for(Kupac kupac: listaKupaca){
       
       model.addRow(new Object[]{kupac.getSifraKupca(),kupac.getNazivKupca(),kupac.getOIBKupca(),kupac.getAdresaKupca(),kupac.getMailKupca(),kupac.getKontaktBrojKupca()});
       }
       
    }
private void zamjeni(){
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
}
