/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isproizvodnjelijekova;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Shpekula
 */
public class EvidencijaSirovine extends javax.swing.JFrame {
SQLSirovine sqlsirovine = new SQLSirovine();
    /**
     * Creates new form EvidencijaSirovine
     */
    public EvidencijaSirovine() {
        initComponents();
        popuniSirovine();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSifraSirovine = new javax.swing.JTextField();
        txtNazivSirovine = new javax.swing.JTextField();
        cmbSirovine = new javax.swing.JComboBox<>();
        btnIzmjeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnOcisti = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtKolicinaSirovine = new javax.swing.JTextField();
        btnSpremi = new javax.swing.JButton();
        btnPovratak = new javax.swing.JButton();
        btnPopisSirovina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Evidencija Sirovina");

        jLabel2.setText("Šifra:");

        jLabel4.setText("Naziv:");

        cmbSirovine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSirovineActionPerformed(evt);
            }
        });

        btnIzmjeni.setText("Izmjeni");
        btnIzmjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnOcisti.setText("Očisti");
        btnOcisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiActionPerformed(evt);
            }
        });

        jLabel5.setText("Količina:");

        btnSpremi.setText("Spremi");
        btnSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremiActionPerformed(evt);
            }
        });

        btnPovratak.setText("Povratak na izbornik");
        btnPovratak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPovratakActionPerformed(evt);
            }
        });

        btnPopisSirovina.setText("Popis sirovina");
        btnPopisSirovina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopisSirovinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSpremi)
                        .addGap(67, 67, 67)
                        .addComponent(btnIzmjeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSifraSirovine)
                            .addComponent(txtNazivSirovine)
                            .addComponent(txtKolicinaSirovine))
                        .addGap(39, 39, 39)
                        .addComponent(cmbSirovine, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnOcisti)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPopisSirovina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPovratak)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSifraSirovine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSirovine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNazivSirovine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKolicinaSirovine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOcisti)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmjeni)
                    .addComponent(btnObrisi)
                    .addComponent(btnSpremi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPovratak)
                    .addComponent(btnPopisSirovina))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSpremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremiActionPerformed
        // TODO add your handling code here:
        int sifraSirovine = Integer.parseInt(txtSifraSirovine.getText());
        String nazivSirovine = txtNazivSirovine.getText();
        int kolicinaSirovine = Integer.parseInt(txtKolicinaSirovine.getText());
        
        Sirovine sirovine = new Sirovine();
        sirovine.setSifraSirovine(sifraSirovine);
        sirovine.setNazivSirovine(nazivSirovine);
        sirovine.setKolicinaSirovine(kolicinaSirovine);
        
        sqlsirovine.spremi(sirovine);
        
        sifraSirovine += 1;
        
        //txtSifraSirovine sifraSirovine;
        autoISirovine();
        txtKolicinaSirovine.setText("");
        txtNazivSirovine.setText("");
        
        //ovdje kreirati objekt i poslati putem SQL tablice, odnosno u bazu podataka
        
    }//GEN-LAST:event_btnSpremiActionPerformed

    private void btnIzmjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjeniActionPerformed
        // TODO add your handling code here:
        int sifraSirovine = Integer.parseInt(txtSifraSirovine.getText());
        String nazivSirovine = txtNazivSirovine.getText();
        int kolicinaSirovine = Integer.parseInt(txtKolicinaSirovine.getText());
        
        Sirovine sirovine = new Sirovine();
        sirovine.setSifraSirovine(sifraSirovine);
        sirovine.setNazivSirovine(nazivSirovine);
        sirovine.setKolicinaSirovine(kolicinaSirovine);
        
        sqlsirovine.IzmjenaSVE(sirovine);
        
        cmbSirovine.setModel(new DefaultComboBoxModel());
        popuniSirovine();
                
    }//GEN-LAST:event_btnIzmjeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        // TODO add your handling code here:
        Sirovine sirovine = new Sirovine();
        int sifraSirovine = Integer.parseInt(txtSifraSirovine.getText());
        sirovine.setSifraSirovine(sifraSirovine);
        sqlsirovine.Brisanje(sirovine);
        
        cmbSirovine.setModel(new DefaultComboBoxModel());
        popuniSirovine();
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed
        // TODO add your handling code here:
        autoISirovine();
        txtNazivSirovine.setText("");
        txtKolicinaSirovine.setText("");
        
        btnSpremi.setVisible(true);
    }//GEN-LAST:event_btnOcistiActionPerformed

    private void cmbSirovineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSirovineActionPerformed
        // TODO add your handling code here:
        Sirovine selSirovine = (Sirovine)cmbSirovine.getSelectedItem();
        txtSifraSirovine.setText(Integer.toString(selSirovine.getSifraSirovine()));
        txtNazivSirovine.setText(selSirovine.getNazivSirovine());
        txtKolicinaSirovine.setText(Integer.toString(selSirovine.getKolicinaSirovine()));
        
        
        btnSpremi.setVisible(false);
        
    }//GEN-LAST:event_cmbSirovineActionPerformed

    private void btnPovratakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPovratakActionPerformed
        // TODO add your handling code here:
        GlavniIzbornik gi = new GlavniIzbornik();
        gi.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPovratakActionPerformed

    private void btnPopisSirovinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopisSirovinaActionPerformed
        // TODO add your handling code here:
        PopisSirovina ps = new PopisSirovina();
        ps.setVisible(true);
    }//GEN-LAST:event_btnPopisSirovinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvidencijaSirovine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvidencijaSirovine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvidencijaSirovine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvidencijaSirovine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvidencijaSirovine().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmjeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnPopisSirovina;
    private javax.swing.JButton btnPovratak;
    private javax.swing.JButton btnSpremi;
    private javax.swing.JComboBox<Sirovine> cmbSirovine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtKolicinaSirovine;
    private javax.swing.JTextField txtNazivSirovine;
    private javax.swing.JTextField txtSifraSirovine;
    // End of variables declaration//GEN-END:variables
private void popuniSirovine(){
    ArrayList<Sirovine>listaSirovina = sqlsirovine.listaSirovina();
    for(Sirovine sirovine: listaSirovina){
       cmbSirovine.addItem(sirovine);
    }
}

private void autoISirovine()
{
    ArrayList<Sirovine> listaSirovina = sqlsirovine.listaSirovina();
    int sifra = 0;
    for(Sirovine sirovine: listaSirovina)
    {
        sifra = sirovine.getSifraSirovine();
    }
    if (sifra == 0)
    {
        sifra = 1;
        txtSifraSirovine.setText(Integer.toString(sifra));
    }
    else
    {
        txtSifraSirovine.setText(Integer.toString(sifra + 1));
    }
}
}