/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isproizvodnjelijekova;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.JTextField;

/**
 *
 * @author Shpekula
 */
public class IzradaProizvoda extends javax.swing.JFrame {
SQLGotovProizvod sqlproizvod = new SQLGotovProizvod();
SQLAmbalaza sqlambalaza = new SQLAmbalaza();
SQLPoluproizvod sqlpp = new SQLPoluproizvod();
SQLPakiranje sqlpakiranje = new SQLPakiranje();
    /**
     * Creates new form IzradaProizvoda
     */
    public IzradaProizvoda() {
        initComponents();
        popuniProizvod();
        datum();
        postavljanjeDatuma();
        btnPakiraj.setVisible(false);
        autoIpakiranje();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbProizvod = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSifraProizvoda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNazivProizvoda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSifraAmbalaze = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSifraPP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPotrebnaKolicina = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtKolicinaProizvoda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUkupnoPakiranje = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtKolicinaPP = new javax.swing.JTextField();
        btnPakiraj = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnPovratak = new javax.swing.JButton();
        txtDatum = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtRokValjanosti = new javax.swing.JTextField();
        Datum = new com.toedter.calendar.JDateChooser();
        btnPrihvatiOdabraniDatum = new javax.swing.JButton();
        txtSifraPakiranja = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProizvodActionPerformed(evt);
            }
        });

        jLabel1.setText("Odaberi proizvod:");

        jLabel2.setText("Šifra proizvoda:");

        txtSifraProizvoda.setEditable(false);

        jLabel3.setText("Naziv proizvoda:");

        txtNazivProizvoda.setEditable(false);

        jLabel4.setText("Šifra ambalaže:");

        txtSifraAmbalaze.setEditable(false);

        jLabel5.setText("Šifra poluproizvoda:");

        txtSifraPP.setEditable(false);

        jLabel6.setText("Potrebna količina:");

        txtPotrebnaKolicina.setEditable(false);

        jLabel7.setText("Količina proizvoda:");

        txtKolicinaProizvoda.setEditable(false);

        jLabel8.setText("Ukupano za pakiranje:");

        txtUkupnoPakiranje.setEditable(false);

        jLabel9.setText("Količina poluproizvoda:");

        txtKolicinaPP.setEditable(false);

        btnPakiraj.setText("Pakiraj");
        btnPakiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPakirajActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Pakiranje");

        btnPovratak.setText("Povratak na izbornik");
        btnPovratak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPovratakActionPerformed(evt);
            }
        });

        txtDatum.setEditable(false);

        jLabel11.setText("Datum roka valjanosti:");

        Datum.setDateFormatString("dd.MM.yyyy");

        btnPrihvatiOdabraniDatum.setText("Prihvati odabrani datum");
        btnPrihvatiOdabraniDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrihvatiOdabraniDatumActionPerformed(evt);
            }
        });

        txtSifraPakiranja.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSifraPP, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSifraAmbalaze)
                                    .addComponent(txtSifraProizvoda)
                                    .addComponent(txtNazivProizvoda)
                                    .addComponent(cmbProizvod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtKolicinaProizvoda)
                                    .addComponent(txtKolicinaPP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel11)))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPotrebnaKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRokValjanosti, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUkupnoPakiranje, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Datum, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(btnPakiraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPovratak))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtSifraPakiranja, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPrihvatiOdabraniDatum)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSifraPakiranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSifraProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKolicinaProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSifraAmbalaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSifraPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtKolicinaPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPotrebnaKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtRokValjanosti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Datum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPrihvatiOdabraniDatum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUkupnoPakiranje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPakiraj))
                .addGap(18, 18, 18)
                .addComponent(btnPovratak)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProizvodActionPerformed
        // TODO add your handling code here:
        GotovProizvod selProizvod = (GotovProizvod) cmbProizvod.getSelectedItem();
        
        txtSifraProizvoda.setText(Integer.toString(selProizvod.getSifraProizvoda()));
        txtNazivProizvoda.setText(selProizvod.getNazivProizvoda());
        txtKolicinaProizvoda.setText(Integer.toString(selProizvod.getKolicinaProizvoda()));
        
        int sifraProizvoda = selProizvod.getSifraProizvoda();
        int sifraPP = 0;
        int kolicinaZP = 0;
        
        ArrayList<Ambalaza> listaAmbalaze = sqlambalaza.listaAmbalaze();
        for(Ambalaza am: listaAmbalaze)
        {
            int sifraAmbalaze = am.getSifraAmbalaze();
            sifraPP = am.getSifraPP();
            int sifraProizvod = am.getSifraProizvoda();
            kolicinaZP = am.getKolicinaZP();
            
            if(sifraProizvoda == sifraProizvod)
            {
                txtSifraAmbalaze.setText(Integer.toString(sifraAmbalaze));
                txtSifraPP.setText(Integer.toString(sifraPP));
                txtPotrebnaKolicina.setText(Integer.toString(kolicinaZP));
            }
        }
        
        int kolicinaPolu = 0;
        
        ArrayList<Poluproizvod> listaPoluproizvoda = sqlpp.listaPoluproizvoda();
        for(Poluproizvod pp: listaPoluproizvoda)
        {
            int sifraPolu = pp.getSifraPP();
            String nazivPolu = pp.getNazivPP();
            kolicinaPolu = pp.getKolicinaPP();
            
            if(sifraPP == sifraPolu)
            {
                txtKolicinaPP.setText(Integer.toString(kolicinaPolu));
            }
        }
        
        int ukupnoZP = kolicinaPolu / kolicinaZP;
        txtUkupnoPakiranje.setText(Integer.toString(ukupnoZP));      
        
        
    }//GEN-LAST:event_cmbProizvodActionPerformed

    private void btnPovratakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPovratakActionPerformed
        // TODO add your handling code here:
        GlavniIzbornik gi = new GlavniIzbornik();
        gi.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPovratakActionPerformed

    private void btnPakirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPakirajActionPerformed
        // TODO add your handling code here:
        int sifraPakiranja = Integer.parseInt(txtSifraPakiranja.getText());
        int sifraAmbalaze = Integer.parseInt(txtSifraAmbalaze.getText());
        int kolicinaPakiranih = Integer.parseInt(txtUkupnoPakiranje.getText());
        String datumProizvodnje = txtDatum.getText();
        String rokValjanosti = txtRokValjanosti.getText();
        
        String rok = Datum.toString();
        
        Pakiranje pakiranje = new Pakiranje();
        pakiranje.setSifraPakiranja(sifraPakiranja);
        pakiranje.setSifraAmbalaze(sifraAmbalaze);
        pakiranje.setKolicinaPakiranih(kolicinaPakiranih);
        pakiranje.setDatumProizvodnje(datumProizvodnje);
        pakiranje.setRokValjanosti(rokValjanosti);
        sqlpakiranje.spremi(pakiranje);
        
        int sifraProizvoda = Integer.parseInt(txtSifraProizvoda.getText());
        int kolicinaProizvoda = Integer.parseInt(txtKolicinaProizvoda.getText());
        kolicinaProizvoda += kolicinaPakiranih;
        
        GotovProizvod proizvod = new GotovProizvod();
        proizvod.setSifraProizvoda(sifraPakiranja);
        proizvod.setKolicinaProizvoda(kolicinaProizvoda);
        sqlproizvod.Izmjena(proizvod);
        
        int sifraPolup = Integer.parseInt(txtSifraPP.getText());
        int potrebnaKolicina = Integer.parseInt(txtPotrebnaKolicina.getText());
        int ukupnoKolicina = potrebnaKolicina * kolicinaPakiranih;
        
        int a = 0;
        int b = 1;
        int kolicinaPolup = 0;
        
        ArrayList<Poluproizvod> listaPoluproizvoda = sqlpp.listaPoluproizvoda();
        for(Poluproizvod pp: listaPoluproizvoda)
        {
            int sifraPP = pp.getSifraPP();
            kolicinaPolup = pp.getKolicinaPP();
            if(sifraPolup == sifraPP)
            {
                if(a<b)
                {
                    kolicinaPolup -= ukupnoKolicina;
                }
                a++;
            }
        }
        
        Poluproizvod pp = new Poluproizvod();
        pp.setSifraPP(sifraPolup);
        pp.setKolicinaPP(kolicinaPolup);
        sqlpp.Izmjena(pp);
        
        btnPrihvatiOdabraniDatum.setVisible(true);
        btnPakiraj.setVisible(false);
        
    }//GEN-LAST:event_btnPakirajActionPerformed

    private void btnPrihvatiOdabraniDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrihvatiOdabraniDatumActionPerformed
        // TODO add your handling code here:
        String rok = ((JTextField)Datum.getDateEditor().getUiComponent()).getText();
        txtRokValjanosti.setText(rok);
        
        btnPakiraj.setVisible(true);
        btnPrihvatiOdabraniDatum.setVisible(false);
        
    }//GEN-LAST:event_btnPrihvatiOdabraniDatumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzradaProizvoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzradaProizvoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzradaProizvoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzradaProizvoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IzradaProizvoda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Datum;
    private javax.swing.JButton btnPakiraj;
    private javax.swing.JButton btnPovratak;
    private javax.swing.JButton btnPrihvatiOdabraniDatum;
    private javax.swing.JComboBox<GotovProizvod> cmbProizvod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtKolicinaPP;
    private javax.swing.JTextField txtKolicinaProizvoda;
    private javax.swing.JTextField txtNazivProizvoda;
    private javax.swing.JTextField txtPotrebnaKolicina;
    private javax.swing.JTextField txtRokValjanosti;
    private javax.swing.JTextField txtSifraAmbalaze;
    private javax.swing.JTextField txtSifraPP;
    private javax.swing.JTextField txtSifraPakiranja;
    private javax.swing.JTextField txtSifraProizvoda;
    private javax.swing.JTextField txtUkupnoPakiranje;
    // End of variables declaration//GEN-END:variables
private void popuniProizvod()
{
    ArrayList<GotovProizvod> listaProizvoda = sqlproizvod.listaGotovProizvoda();
    for(GotovProizvod proizvod: listaProizvoda)
    {
        cmbProizvod.addItem(proizvod);
    }
}

private void autoIpakiranje()
{
    ArrayList<Pakiranje> listaPakiranja = sqlpakiranje.listaPakiranja();
    int sifra = 0;
    for(Pakiranje pakiranje: listaPakiranja)
    {
        sifra = pakiranje.getSifraPakiranja();
        if(sifra == 0)
        {
            sifra = 1;
            txtSifraPakiranja.setText(Integer.toString(sifra));
        }
        else
        {
            sifra += 1;
            txtSifraPakiranja.setText(Integer.toString(sifra));
        }
    }
}

private void datum()
{
    String txtDat = new SimpleDateFormat("dd.MM.yyyy", Locale.ENGLISH).format(new Date());
    txtDatum.setText(txtDat);    
}

private String postavljanjeDatuma()
{
    String rok = Datum.toString();
    
    return rok;
}
}