/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isproizvodnjelijekova;

import java.util.ArrayList;

/**
 *
 * @author Shpekula
 */
public class KreirajZaposlenika extends javax.swing.JFrame {
SQLKorisnik sqlkorisnik = new SQLKorisnik();
    /**
     * Creates new form KreirajZaposlenika
     */
    public KreirajZaposlenika() {
        initComponents();
        popuniKorisnika();
        //autoIKorisnik();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        txtSifra = new javax.swing.JTextField();
        txtKorisnickoIme = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtLozinka = new javax.swing.JTextField();
        btnSpremi = new javax.swing.JButton();
        btnIzmjena = new javax.swing.JButton();
        btnBrisanje = new javax.swing.JButton();
        cmbKorisnik = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnOcisti = new javax.swing.JButton();
        btnPovratak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Šifra zaposlenika:");

        jLabel2.setText("Korisničko ime:");

        jLabel3.setText("Status zaposlenika:");

        jLabel4.setText("Lozinka:");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Radnik", "Voditelj" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });

        txtStatus.setEditable(false);

        btnSpremi.setText("Spremi");
        btnSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremiActionPerformed(evt);
            }
        });

        btnIzmjena.setText("Izmjena");
        btnIzmjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjenaActionPerformed(evt);
            }
        });

        btnBrisanje.setText("Brisanje");
        btnBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeActionPerformed(evt);
            }
        });

        cmbKorisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKorisnikActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Kreiranje zaposlenika");

        btnOcisti.setText("Očisti");
        btnOcisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiActionPerformed(evt);
            }
        });

        btnPovratak.setText("Povratak na izbornik");
        btnPovratak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPovratakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOcisti, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtStatus)
                            .addComponent(txtSifra)
                            .addComponent(txtKorisnickoIme)
                            .addComponent(txtLozinka, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbKorisnik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbStatus, 0, 100, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSpremi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzmjena)
                .addGap(96, 96, 96)
                .addComponent(btnBrisanje)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPovratak)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOcisti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrisanje)
                    .addComponent(btnIzmjena)
                    .addComponent(btnSpremi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPovratak)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSpremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremiActionPerformed
        // TODO add your handling code here:
        int sifraKorisnika = Integer.parseInt(txtSifra.getText());
        String nazivKorisnika = txtKorisnickoIme.getText();
        String statusKorisnika = txtStatus.getText();
        String lozinkaKorisnika = txtLozinka.getText();
        
        Korisnik korisnik = new Korisnik();
        korisnik.setSifraKorisnika(sifraKorisnika);
        korisnik.setNazivKorisnika(nazivKorisnika);
        korisnik.setLozinkaKorisnika(lozinkaKorisnika);
        korisnik.setStatusKorisnika(statusKorisnika);
        
        sqlkorisnik.spremi(korisnik);
        
        autoIKorisnik();
        txtKorisnickoIme.setText("");
        txtLozinka.setText("");
        txtStatus.setText("");
                
    }//GEN-LAST:event_btnSpremiActionPerformed

    private void btnIzmjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjenaActionPerformed
        // TODO add your handling code here:
        int sifraKorisnika = Integer.parseInt(txtSifra.getText());
        String nazivKorisnika = txtKorisnickoIme.getText();
        String statusKorisnika = txtStatus.getText();
        String lozinkaKorisnika = txtLozinka.getText();
        
        Korisnik korisnik = new Korisnik();
        korisnik.setSifraKorisnika(sifraKorisnika);
        korisnik.setNazivKorisnika(nazivKorisnika);
        korisnik.setLozinkaKorisnika(lozinkaKorisnika);
        korisnik.setStatusKorisnika(statusKorisnika);
        
        sqlkorisnik.IzmjenaSVE(korisnik);
    }//GEN-LAST:event_btnIzmjenaActionPerformed

    private void btnBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeActionPerformed
        // TODO add your handling code here:
        int sifraKorisnika = Integer.parseInt(txtSifra.getText());
        String nazivKorisnika = txtKorisnickoIme.getText();
        String statusKorisnika = txtStatus.getText();
        String lozinkaKorisnika = txtLozinka.getText();
        
        Korisnik korisnik = new Korisnik();
        korisnik.setSifraKorisnika(sifraKorisnika);
        korisnik.setNazivKorisnika(nazivKorisnika);
        korisnik.setLozinkaKorisnika(lozinkaKorisnika);
        korisnik.setStatusKorisnika(statusKorisnika);
        
        sqlkorisnik.Brisanje(korisnik);
        
    }//GEN-LAST:event_btnBrisanjeActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
        cmbStatus.getSelectedItem().toString();
        String status = (String) cmbStatus.getSelectedItem();
        txtStatus.setText(status);
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void cmbKorisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKorisnikActionPerformed
        // TODO add your handling code here:
        Korisnik selkorisnik = (Korisnik) cmbKorisnik.getSelectedItem();
        txtSifra.setText(Integer.toString(selkorisnik.getSifraKorisnika()));
        txtKorisnickoIme.setText(selkorisnik.getNazivKorisnika());
        txtLozinka.setText(selkorisnik.getLozinkaKorisnika());
        txtStatus.setText(selkorisnik.getStatusKorisnika());
        
    }//GEN-LAST:event_cmbKorisnikActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed
        // TODO add your handling code here:
        autoIKorisnik();
        txtKorisnickoIme.setText("");
        txtLozinka.setText("");
        txtStatus.setText("");
    }//GEN-LAST:event_btnOcistiActionPerformed

    private void btnPovratakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPovratakActionPerformed
        // TODO add your handling code here:
        GlavniIzbornikVoditelja giv = new GlavniIzbornikVoditelja();
        giv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPovratakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KreirajZaposlenika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KreirajZaposlenika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KreirajZaposlenika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KreirajZaposlenika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KreirajZaposlenika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanje;
    private javax.swing.JButton btnIzmjena;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnPovratak;
    private javax.swing.JButton btnSpremi;
    private javax.swing.JComboBox<Korisnik> cmbKorisnik;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JTextField txtLozinka;
    private javax.swing.JTextField txtSifra;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
private void popuniKorisnika()
{
    ArrayList<Korisnik> listaKorisnika = sqlkorisnik.listaKorisnika();
    for(Korisnik korisnik: listaKorisnika)
    {
        cmbKorisnik.addItem(korisnik);
    }
}

private void autoIKorisnik()
{
    ArrayList<Korisnik> listaKorisnika = sqlkorisnik.listaKorisnika();
    int sifra = 0;
    for(Korisnik korisnik: listaKorisnika)
    {
        sifra = korisnik.getSifraKorisnika();
    }
    if (sifra == 0)
    {
        sifra = 1;
        txtSifra.setText(Integer.toString(sifra));
    }
    else
    {
        txtSifra.setText(Integer.toString(sifra + 1));
    }
}
}
